import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Main from '../components/Main'
import styles from '../styles/Home.module.css'

const Home = () => {
  return (
    <div className="bg-green-800 h-screen box-content" >
      <Head>
        <title>Linktree</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relativ">

        <Header />
        <Main />

      </div>


    </div>
  )
}

export default Home;
